version: '3.8'
services:
    scooters-db:
      image: postgres:14.1-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5434:5432'
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data
