# Generated by Django 4.0 on 2022-01-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("payment_external_id", models.CharField(max_length=200, null=True)),
                ("ended_in_allowed_zone", models.BooleanField(null=True)),
                (
                    "city",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="city.city"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "rent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rent.rent"),
                ),
            ],
        ),
    ]
