# Generated by Django 4.0 on 2022-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0003_alter_rent_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="status",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("end", "End"),
                    ("during", "During"),
                    ("break", "Break"),
                ],
                default="start",
                max_length=10,
            ),
        ),
    ]
