# Generated by Django 4.0 on 2022-01-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_alter_vehicle_latitude_alter_vehicle_longitude"),
        ("rent", "0004_alter_rent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="total_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="rent",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rents",
                to="vehicle.vehicle",
            ),
        ),
    ]
