# Generated by Django 4.0 on 2022-01-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0005_rent_total_cost_alter_rent_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentbreak",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rentbreak",
            name="start_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
