# Generated by Django 4.0 on 2022-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0007_alter_rentbreak_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rent",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="rentbreak",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
