# Generated by Django 4.0 on 2022-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
