# Generated by Django 4.0 on 2022-01-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0004_alter_rating_description_alter_rating_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
