# Generated by Django 4.0 on 2022-01-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0005_alter_rating_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
    ]
