# Generated by Django 4.0 on 2022-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0006_alter_rating_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
