# Generated by Django 4.0 on 2022-01-21 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0007_alter_rating_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
