# Generated by Django 4.0 on 2022-01-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faultreport",
            name="date_reported",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
