# Generated by Django 4.0 on 2022-01-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_alter_faultreport_date_reported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faultreport",
            name="malfunction_type",
            field=models.CharField(
                choices=[
                    ("stuck", "Stuck"),
                    ("broken", "Broken"),
                    ("destroyed", "Destroyed"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
