# Generated by Django 4.0 on 2022-01-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vehicle",
            unique_together={("serial_number", "vehicle_type")},
        ),
    ]
