# Generated by Django 4.0 on 2022-01-21 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_alter_vehicle_latitude_alter_vehicle_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="battery_level",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="last_updated_timestamp",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
